### PR TITLE
Add git-crypt to git image

### PR DESCRIPTION
**Pull request by gabro**
[git-crypt](https://github.com/AGWA/git-crypt) [just landed on buildroot](https://git.busybox.net/buildroot/commit/?id=8c43f5fd37e2cb4298c042b07b1ba017ebcd9256) and it's a useful addition for stuff like https://github.com/concourse/git-resource/issues/7

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gabro Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/buildroot-images&pullRequestId=5)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/buildroot-images&pullRequestId=5) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gabro Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/buildroot-images&pullRequestId=5)!

**Comment by pivotal-issuemaster** [comment]
@gabro Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/buildroot-images&pullRequestId=5)!

**Comment by dhinus** [comment]
@vito the latest stable release of buildroot (2017.02) now includes a `git-crypt` package. Do you reckon this can merged?

**Comment by chendrix** [comment]
Hey there!

Are y'all also planning on making a PR to the git resource itself to add this support? It'd be great to have both to merge at once. 

I can't see any immediate problems with this PR though, so I'll just wait until your response before merging.

**Comment by gabro** [comment]
Yep, that's the plan!
As soon as we have this merged we can work and test the API for the git resource :)

--
gabriele
~ buildo

**Comment by chendrix** [comment]
Great!

**Pull request merged**
